name: bitinfo
channels:
  - conda-forge
dependencies:
  - python
  - julia
  - pyjulia
  - ca-certificates
  - openssl
  - numpy
  - matplotlib
  - pyqt
  - pytest
  - pytest-xdist
  - pooch
  - xarray
  - dask
  - zarr
  - netcdf4
  - pip
# prefix: /Users/haukeschulz/mambaforge/envs/bitinfo
