name: bitinfo
channels:
  - conda-forge
dependencies:
  - python=3.8.8
  - julia
  - pyjulia
  - matplotlib-base
  - numpy
  - xarray
  - dask-core
  - jupyterlab
  - netcdf4
  - zarr
  - cfgrib
  - cdo
  - python-cdo
  - pytest
  - nb_conda_kernels
  - pip
  - pip:
    - git+https://github.com/observingClouds/numcodecs@bitround
