name: bitinfo
channels:
  - conda-forge
dependencies:
  - python
  - julia
  - pyjulia
  - ca-certificates
  - openssl
  - numpy
  - matplotlib
  - pyqt
  - pytest
  - xarray
  - zarr
  - netcdf4
# prefix: /Users/haukeschulz/mambaforge/envs/bitinfo
