name: bitinfo-docs
channels:
  - conda-forge
dependencies:
  - python
  - matplotlib-base
  - numpy
  - pooch
  - xarray
  - dask-core
  - jupyterlab
  - netcdf4
  - zarr
  - cfgrib
  - prefect>=1.0.0,<2.0
  - cmcrameri
  - julia
  - tqdm
  - pytest
  - sphinx!=4.4.0
  - sphinx-copybutton
  - sphinx-book-theme>=0.1.7
  - myst-nb
  - numcodecs>=0.10.0
  - intake-xarray
  - s3fs
  - pip
  - pip:
    - -e ../.
